// This file is GENERATED by buildPlugin.mjs script
import {PluginEnv} from "lib/plugin/PluginEnv"
export const PLUGIN_ENV = new PluginEnv({
    env: "dev",
    pluginName: "Build Plugin Example",
    pluginId: "author_id__build_plugin_example__v0_1_0_dev",
    pluginVersion: "0.1.0",
    author: "Some Author"
})
